In [146]:
import pandas as pd
import sqlite3
import os

if not os.getcwd().endswith('/run'):
    os.chdir('run')

DBNAME = "state.db"

In [147]:
with sqlite3.connect(DBNAME) as conn:
    df = pd.read_sql("SELECT * FROM pages", conn)
df

,sid,url,depth,status,attempts,inserted_at,last_attempt,error
0,1,https://books.toscrape.com/index.html,0,visited,1,2025-07-08 00:34:58,2025-07-08 00:34:58,None
1,2,https://books.toscrape.com/catalogue/category/...,1,visited,1,2025-07-08 00:34:59,2025-07-08 00:34:59,None
2,3,https://books.toscrape.com/catalogue/category/...,1,visited,1,2025-07-08 00:34:59,2025-07-08 00:35:01,None
3,4,https://books.toscrape.com/catalogue/category/...,1,visited,1,2025-07-08 00:34:59,2025-07-08 00:35:02,None
4,5,https://books.toscrape.com/catalogue/category/...,1,visited,1,2025-07-08 00:34:59,2025-07-08 00:35:03,None
...,...,...,...,...,...,...,...,...
291,292,https://books.toscrape.com/catalogue/maude-188...,2,queued,0,2025-07-08 00:37:46,None,None
292,293,https://books.toscrape.com/catalogue/behind-cl...,2,queued,0,2025-07-08 00:37:46,None,None
293,294,https://books.toscrape.com/catalogue/you-cant-...,2,queued,0,2025-07-08 00:37:46,None,None
294,295,https://books.toscrape.com/catalogue/page-1.html,2,queued,0,2025-07-08 00:37:46,None,None
295,296,https://books.toscrape.com/catalogue/page-3.html,2,queued,0,2025-07-08 00:37:46,None,None

In [148]:
with sqlite3.connect(DBNAME) as conn:
    df = pd.read_sql("SELECT * FROM pages WHERE status = 'failed'", conn)
df

,sid,url,depth,status,attempts,inserted_at,last_attempt,error
0,13,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-08 00:34:59,2025-07-08 00:35:23,405 Client Error: OK for url: https://books.to...
1,14,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-08 00:34:59,2025-07-08 00:35:24,400 Client Error: OK for url: https://books.to...
2,15,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-08 00:34:59,2025-07-08 00:35:25,422 Client Error: OK for url: https://books.to...
3,16,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-08 00:34:59,2025-07-08 00:35:27,405 Client Error: OK for url: https://books.to...
4,19,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-08 00:34:59,2025-07-08 00:35:35,405 Client Error: OK for url: https://books.to...
...,...,...,...,...,...,...,...,...
69,76,https://books.toscrape.com/catalogue/see-ameri...,2,failed,2,2025-07-08 00:35:01,2025-07-08 00:37:52,502 Server Error: OK for url: https://books.to...
70,78,https://books.toscrape.com/catalogue/under-the...,2,failed,2,2025-07-08 00:35:01,2025-07-08 00:37:58,500 Server Error: OK for url: https://books.to...
71,80,https://books.toscrape.com/catalogue/the-great...,2,failed,2,2025-07-08 00:35:01,2025-07-08 00:38:02,502 Server Error: OK for url: https://books.to...
72,81,https://books.toscrape.com/catalogue/a-year-in...,2,failed,2,2025-07-08 00:35:01,2025-07-08 00:38:06,502 Server Error: OK for url: https://books.to...
73,97,https://books.toscrape.com/catalogue/hide-away...,2,failed,2,2025-07-08 00:35:02,2025-07-08 00:38:26,410 Client Error: OK for url: https://books.to...