In [61]:
import pandas as pd
import sqlite3
import os

if not os.getcwd().endswith('/run'):
    os.chdir('run')

DBNAME = "state.db"

In [62]:
with sqlite3.connect(DBNAME) as conn:
    df = pd.read_sql("SELECT * FROM pages", conn)
df

,sid,url,depth,status,retries,inserted_at,last_attempt
0,1,https://books.toscrape.com/index.html,0,visited,0,2025-07-07 22:06:54,2025-07-07 22:06:54
1,2,https://books.toscrape.com/catalogue/category/...,1,visited,0,2025-07-07 22:06:58,2025-07-07 22:06:59
2,3,https://books.toscrape.com/catalogue/category/...,1,visited,0,2025-07-07 22:06:58,2025-07-07 22:07:00
3,4,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:02
4,5,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:03
...,...,...,...,...,...,...,...
424,425,https://books.toscrape.com/catalogue/amid-the-...,2,queued,0,2025-07-07 22:08:26,None
425,426,https://books.toscrape.com/catalogue/amid-the-...,2,queued,0,2025-07-07 22:08:26,None
426,427,https://books.toscrape.com/catalogue/tipping-t...,2,queued,0,2025-07-07 22:08:33,None
427,428,https://books.toscrape.com/catalogue/a-light-i...,2,queued,0,2025-07-07 22:08:42,None
428,429,https://books.toscrape.com/catalogue/the-comin...,2,queued,0,2025-07-07 22:08:49,None

In [63]:
df[df.url.str.endswith('.txt')]

,sid,url,depth,status,retries,inserted_at,last_attempt
10,11,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:26
23,24,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:50
26,27,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:55
36,37,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:05
38,39,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:09
...,...,...,...,...,...,...,...
403,404,https://books.toscrape.com/catalogue/category/...,2,queued,0,2025-07-07 22:08:17,None
412,413,https://books.toscrape.com/catalogue/category/...,2,queued,0,2025-07-07 22:08:23,None
416,417,https://books.toscrape.com/catalogue/eat-fat-g...,2,queued,0,2025-07-07 22:08:24,None
422,423,https://books.toscrape.com/catalogue/category/...,2,queued,0,2025-07-07 22:08:26,None
427,428,https://books.toscrape.com/catalogue/a-light-i...,2,queued,0,2025-07-07 22:08:42,None

In [64]:
with sqlite3.connect(DBNAME) as conn:
    df = pd.read_sql("SELECT * FROM pages WHERE status = 'failed'", conn)
df

,sid,url,depth,status,retries,inserted_at,last_attempt
0,4,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:02
1,5,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:03
2,7,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:12
3,9,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:23
4,10,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:24
5,11,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:26
6,12,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:29
7,13,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:31
8,14,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:33
9,15,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:34
10,17,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:36
11,19,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:41
12,20,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:44
13,24,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:50
14,27,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:55
15,28,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:56
16,30,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:58
17,31,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:07:58
18,33,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:00
19,35,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:03
20,37,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:05
21,39,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:09
22,41,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:14
23,43,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:19
24,44,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:20
25,46,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:22
26,51,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:28
27,52,https://books.toscrape.com/catalogue/category/...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:29
28,56,https://books.toscrape.com/catalogue/sharp-obj...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:36
29,57,https://books.toscrape.com/catalogue/sapiens-a...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:37
30,58,https://books.toscrape.com/catalogue/sapiens-a...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:39
31,60,https://books.toscrape.com/catalogue/the-requi...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:43
32,61,https://books.toscrape.com/catalogue/the-dirty...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:44
33,63,https://books.toscrape.com/catalogue/the-boys-...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:47
34,65,https://books.toscrape.com/catalogue/starving-...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:51
35,66,https://books.toscrape.com/catalogue/shakespea...,1,failed,1,2025-07-07 22:06:58,2025-07-07 22:08:52

In [65]:
RETRY_CODES = (429, 500, 502, 503, 504)
NON_RETRY_CODES = (400, 401, 403, 404, 405, 410, 422, 501)

RETRY_CODES + NON_RETRY_CODES

(429, 500, 502, 503, 504, 400, 401, 403, 404, 405, 410, 422, 501)