In [2]:
import pandas as pd
import sqlite3

In [7]:
conn = sqlite3.connect("crawler.db")
df = pd.read_sql("SELECT * FROM visited", conn)
conn.close()
df[:20]

                                                  url  depth
0                         https://books.toscrape.com/      0
1               https://books.toscrape.com/index.html      1
2   https://books.toscrape.com/catalogue/category/...      1
3   https://books.toscrape.com/catalogue/category/...      1
4   https://books.toscrape.com/catalogue/category/...      1
5   https://books.toscrape.com/catalogue/category/...      1
6   https://books.toscrape.com/catalogue/category/...      1
7   https://books.toscrape.com/catalogue/category/...      1
8   https://books.toscrape.com/catalogue/category/...      1
9   https://books.toscrape.com/catalogue/category/...      1
10  https://books.toscrape.com/catalogue/category/...      1
11  https://books.toscrape.com/catalogue/category/...      1
12  https://books.toscrape.com/catalogue/category/...      1
13  https://books.toscrape.com/catalogue/category/...      1
14  https://books.toscrape.com/catalogue/category/...      1
15  https://books.toscrape.com/catalogue/category/...      1
16  https://books.toscrape.com/catalogue/category/...      1
17  https://books.toscrape.com/catalogue/category/...      1
18  https://books.toscrape.com/catalogue/category/...      1
19  https://books.toscrape.com/catalogue/category/...      1

In [12]:
with sqlite3.connect("crawler.db") as conn:
    df = pd.read_sql("SELECT * FROM failed", conn)
df

Empty DataFrame
Columns: [url, error_count]
Index: []